teams:
  - name: QA Chapter
    slack_channel: "#qa-automation"
    schedule: "0 6 * * 1-5"  # 08:00 Stockholm time every weekday
    repositories:
      - e2e-tests
      - e2e-apps
      - test-precondition
      - workflow-utilities
      - pr_reminder_bot
      - broken-links
    members:
      - davidmateodev
      - AnatoliTsoi
      - volodimirchernov
      - fkavakli
      - olenzing
  - name: Book Team - Web
    slack_channel: "#book-webbies"
    schedule: "0 6 * * 1"  # 08:00 Stockholm time every Monday
    repositories:
      - strawberry_web
      - spec_content-resources
      - Service-MVP
      - strawberry_portal
      - strawberry_edge
      - strawberry_map
      - strawberry_terraform
    members:
      - prickar
      - mattiasmucherie
      - ell-ska
      - davidmateodev
