teams:
  - name: QA Chapter
    slack_channel: "#qa-pull-requests"
    repositories:
      - e2e-tests
      - e2e-apps
      - test-precondition
      - workflow-utilities
      - pr_reminder_bot
      - broken-links
      - test_dashboard
    members:
      - davidmateodev
      - AnatoliTsoi
      - volodimirchernov
      - fkavakli
      - olenzing