teams:
  - name: QA Chapter
    slack_channel: "#team-chapter-qa"
    repositories:
      - e2e-tests
      - e2e-apps
      - test-precondition
    members:
      - davidmateodev
      - christopherlingcarragher
      - AnatoliTsoi
      - volodimirchernov
  - name: Book Team - Web
    slack_channel: "#team-book"
    repositories:
      - strawberry_web
      - spec_content-resources
      - Service-MVP
      - strawberry_portal
      - strawberry_edge
      - strawberry_map
      - strawberry_terraform
    members:
      - prickar
      - ziaahmad
      - mattiasmucherie
      - ell-ska