name: PR Reminder Bot

on:
  schedule:
    - cron: '0 6 * * *'  # Run once daily at 08:00 Stockholm time
  workflow_dispatch:
    inputs:
      team:
        description: 'Select a team to run the reminder for'
        required: true
        type: choice
        options:
          - All
          - QA Chapter
          - Book Team - Web
        default: All

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TEAM_NAME: ${{ github.event.inputs.team }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_ORG: ${{ secrets.GH_ORG }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run PR Reminder bot
        run: npm start